const ACTIONS = {
  APPLY_NUMBER: 'APPLY_NUMBER',
  CLEAR_NUMBER: 'CLEAR_NUMBER',
  APPLY_MEMORY: 'APPLY_MEMORY',
  CLEAR_MEMORY: 'CLEAR_MEMORY',
  CHANGE_OPERATION: 'CHANGE_OPERATION',
}

const OPERATIONS = {
  ADD: '+',
  SUB: '-',
  MUL: '*',
}

export { ACTIONS, OPERATIONS }
