const ACTIONS = {
  APPLY_NUMBER: 'APPLY_NUMBER',
  CLEAR_NUMBER: 'CLEAR_NUMBER',
  APPLY_MEMORY: 'APPLY_MEMORY',
  CLEAR_MEMORY: 'CLEAR_MEMORY',
  CHANGE_OPERATION: 'CHANGE_OPERATION',
}

const OPERATIONS = {
  ADD: '+',
  SUB: '-',
  MUL: '*',
}

const BUTTONS = {
  ADD_MEMORY: 'M+',
  USE_MEMORY: 'MR',
  CLEAR_MEMORY: 'MC',
  CLEAR_TOTAL: 'CE',
}

export { ACTIONS, OPERATIONS, BUTTONS }
